/*
This file is part of Cuidando Bem.

    Cuidando Bem is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Cuidando Bem is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Cuidando Bem.  If not, see <http://www.gnu.org/licenses/>.
*/

define(["text!../html/dialog/dialog.html","text!../html/dialog/dialogButtonTemplate.html"],function(e,t){function c(t){$(t).append(e)}function h(e){l?d(e):p(e)}function p(e){dialog=e,$(s).show(),$(n).show("fade",{duration:200,complete:function(){d(e)}}),l=!0,$(document).keydown(function(e){switch(e.which){case 38:$(".dialog_reread").click();break;case 40:$(".dialog_right").click();break;case 49:$(".dialog_button[value='1']").click();break;case 50:$(".dialog_button[value='2']").click();break;case 51:$(".dialog_button[value='3']").click();break;case 52:$(".dialog_button[value='4']").click();break;case 53:$(".dialog_button[value='5']").click()}})}function d(e){function f(){$(r).first().show(t,{duration:a,progress:function(){$(i.show(t))},complete:function(){e.getText()!=""?$(o).show(s,{duration:a,complete:function(){$(u).show(s)}}):$(u).show(s)}})}$(r).text(e.getSpeakerName()),$(i).removeClass(),$(i).addClass(e.getSpeakerCssClass()),$(i).show(),$(o).text(e.getText()),$(".dialog_reread").click(function(){$("<span>"+e.getSpeakerName()+": </span>").appendTo("#accessible_log"),e.getText()!=""&&$("<span>"+e.getText()+"</span><br>").appendTo("#accessible_log")}),$(".dialog_reread").click(),v(e.getOptions(),e.getRandomize());var t="blind",s="clip",a=250;l==0?($(n+" div").hide(),$(r).first().show(),$(i).show(),$(o).show(),$(u).show()):($(o).hide(),$(u).hide(),$(r).first().show(),$(i).show(),$(o).show(),$(u).show())}function v(e,t){x();if(e.length==1&&e[0].text==""){var n=$(a);n.click(e[0].actionFunction),n.on(),$(a).removeClass("off"),$(a).addClass("on"),$(a).append(n)}else E(e,t)}function m(){$(document).unbind("keydown"),$(r).hide(),$(i).hide(),$(o).hide(),$(u).hide(),$(s).hide(),$(n).hide("fade",200),l=!1;if(!l){var e=0;$(document).keydown(function(t){if($(".action_button:visible").length)var n=$.merge($(".interactiveObject:visible"),$(".action_button:visible"));else var n=$(".interactiveObject:visible");n.length!=0&&(t.which==40?(e>=n.length-1?e=0:e++,$(n[e]).focus()):t.which==38?(e>0?e--:e=n.length-1,$(n[e]).focus()):t.which==13&&e!=-1&&$(n[e]).click())})}}function g(){}function y(){}function b(e,n){var r=$(t);r.click(e.actionFunction),$(".text",r).text(e.text),r.attr("value",n),$(u).append(r)}function w(e){var t=e.length,n,r;while(t)r=Math.floor(Math.random()*t--),n=e[t],e[t]=e[r],e[r]=n;return e}function E(e,t){var n,r;t&&(e=w(e));for(n=0;n<e.length;n++)b(e[n],n+1),e.length==1?r="única":r=n+1,$("<span>Opção "+r+": "+e[n].text+"</span><br>").appendTo("#accessible_log")}function S(e){$("."+e.getCssClass(),element).remove()}function x(){$(u).empty(),$(a).empty(),$(a).off(),$(a).removeClass("on"),$(a).addClass("off")}var n="#dialogBar",r=".dialog_charName",i="#dialog_charImg",s="#dialogBar-mask",o=".dialog_mainText",u=".dialog_options",a=".dialog_right",f=".dialog_reread",l=!1;return{init:c,show:h,close:m}});