/*
 This file is part of Cuidando Bem.

 Cuidando Bem is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Cuidando Bem is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Cuidando Bem.  If not, see <http://www.gnu.org/licenses/>.
 */

define(["require","text!../html/freqRespiratoria/freqRespiratoria.html","Player"],function(t){function e(){this.x,this.y,this.frameTime,this.accumulator=0,this.frameTotal,this.frameCounter=0,this.cyclesPerMinute,this.img=[],this.hasToDraw=!1,this.width,this.height,this.srWidth,this.srHeight,this.update=function(){for(this.accumulator+=p.time;this.accumulator>=this.frameTime;)this.frameCounter++,this.frameCounter=this.frameCounter%this.frameTotal,this.hasToDraw=!0,this.accumulator-=this.frameTime},this.draw=function(t){if(this.hasToDraw){var e=t.getContext("2d"),i=(this.frameCounter*this.width,this.img[this.frameCounter]);e.drawImage(i,0,0,this.srWidth,this.srHeight,this.x,this.y,this.width,this.height)}}}function a(t){$(t).append(l);var e=$(d)[0];e.setAttribute("width",800),e.setAttribute("height",600)}function r(){g.stopAll(),$(d).show(),y.angle=-Math.PI/2,y.accumulator=0,T.frameCounter=0,p.accumulator=0,x=f.playing,p.last=(new Date).getTime(),c()}function o(){$(d).hide(),x=f.stopped,g.stop(),clearInterval(u),clearInterval(h)}function s(){for(T.update(),y.accumulator+=p.time;y.accumulator>=y.time;)y.angle+=2*Math.PI/1e3/60,y.accumulator-=y.time}function n(t){ctx=t.getContext("2d"),ctx.clearRect(0,0,800,600),T.draw(t),ctx.drawImage(y.img,0,0,350,600,601,135,200,330),ctx.beginPath(),ctx.moveTo(y.x,y.y-y.radius),ctx.lineTo(y.x,y.y-y.radius+y.line),ctx.moveTo(y.x,y.y+y.radius),ctx.lineTo(y.x,y.y+y.radius-y.line),ctx.moveTo(y.x-y.radius,y.y),ctx.lineTo(y.x-y.radius+y.line,y.y),ctx.moveTo(y.x+y.radius,y.y),ctx.lineTo(y.x+y.radius-y.line,y.y),ctx.lineWidth=2,ctx.strokeStyle="rgba(0,0,0,130)",ctx.stroke(),ctx.beginPath(),px=Math.cos(y.angle)*y.radius+y.x,py=Math.sin(y.angle)*y.radius+y.y,ctx.moveTo(y.x,y.y),ctx.lineTo(px,py),ctx.lineWidth=5,ctx.strokeStyle="rgba(0,0,0,255)",ctx.stroke()}function c(){for(p.now=(new Date).getTime(),p.passed=p.now-p.last,p.last=p.now,p.accumulator+=p.passed;p.accumulator>=p.time;)s(),p.accumulator-=p.time;n($(d)[0]),x==f.playing&&window.requestAnimationFrame(c)}function m(t){T.cyclesPerMinute=t,T.frameTime=6e4/T.cyclesPerMinute/T.frameTotal}var h,u,l=t("text!../html/freqRespiratoria/freqRespiratoria.html"),d="#freqRespiratoria",g=t("Player"),f={playing:0,stopped:1},x=f.stopped,p={last:void 0,passed:void 0,now:void 0,accumulator:0,time:void 0,rate:60},y={x:700,y:300,radius:60,angle:0,line:20,img:void 0,accumulator:0,time:1};p.time=1e3/p.rate;var T=new e;T.x=50,T.y=180,T.width=400,T.height=240,T.srWidth=1920,T.srHeight=1152,T.frameTotal=12,T.cyclesPerMinute=18,T.frameTime=6e4/T.cyclesPerMinute/T.frameTotal;var w=0;for(i=0;i<T.frameTotal;i++){T.img.push(new Image),T.img[i].onload=function(){w++};var v=T.img[i];i<10&&(i="0"+i),v.src="./images/modalScenes/01_"+i+".png"}return y.img=new Image,y.img.src="./images/modalScenes/relogioDigital.png",y.img.onLoad=function(){},{init:a,setFr:m,open:r,close:o}});