/*
This file is part of Cuidando Bem.

    Cuidando Bem is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Cuidando Bem is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Cuidando Bem.  If not, see <http://www.gnu.org/licenses/>.
*/

define(["require","text!../html/freqRespiratoria/freqRespiratoria.html"],function(t){function e(){this.x,this.y,this.frameTime,this.accumulator=0,this.frameTotal,this.frameCounter=0,this.cyclesPerMinute,this.img=[],this.hasToDraw=!1,this.width,this.height,this.srWidth,this.srHeight,this.update=function(){for(this.accumulator+=g.time;this.accumulator>=this.frameTime;)this.frameCounter++,this.frameCounter=this.frameCounter%this.frameTotal,this.hasToDraw=!0,this.accumulator-=this.frameTime},this.draw=function(t){if(this.hasToDraw){var i=t.getContext("2d"),e=(this.frameCounter*this.width,this.img[this.frameCounter]);i.drawImage(e,0,0,this.srWidth,this.srHeight,this.x,this.y,this.width,this.height)}}}function a(t){$(t).append(h);var i=$(u)[0];i.setAttribute("width",800),i.setAttribute("height",600)}function r(){$(u).show(),f.angle=-Math.PI/2,f.accumulator=0,x.frameCounter=0,g.accumulator=0,g.last=(new Date).getTime(),d=l.playing,c()}function o(){$(u).hide(),d=l.stopped}function s(){for(x.update(),f.accumulator+=g.time;f.accumulator>=f.time;)f.angle+=2*Math.PI/1e3/60,f.accumulator-=f.time}function n(t){ctx=t.getContext("2d"),ctx.clearRect(0,0,800,600),x.draw(t),ctx.drawImage(f.img,0,0,350,600,601,135,200,330),ctx.beginPath(),ctx.moveTo(f.x,f.y-f.radius),ctx.lineTo(f.x,f.y-f.radius+f.line),ctx.moveTo(f.x,f.y+f.radius),ctx.lineTo(f.x,f.y+f.radius-f.line),ctx.moveTo(f.x-f.radius,f.y),ctx.lineTo(f.x-f.radius+f.line,f.y),ctx.moveTo(f.x+f.radius,f.y),ctx.lineTo(f.x+f.radius-f.line,f.y),ctx.lineWidth=2,ctx.strokeStyle="rgba(0,0,0,130)",ctx.stroke(),ctx.beginPath(),px=Math.cos(f.angle)*f.radius+f.x,py=Math.sin(f.angle)*f.radius+f.y,ctx.moveTo(f.x,f.y),ctx.lineTo(px,py),ctx.lineWidth=5,ctx.strokeStyle="rgba(0,0,0,255)",ctx.stroke()}function c(){for(g.now=(new Date).getTime(),g.passed=g.now-g.last,g.last=g.now,g.accumulator+=g.passed;g.accumulator>=g.time;)s(),g.accumulator-=g.time;n($(u)[0]),d==l.playing&&window.requestAnimationFrame(c)}function m(t){x.cyclesPerMinute=t,x.frameTime=6e4/x.cyclesPerMinute/x.frameTotal}var h=t("text!../html/freqRespiratoria/freqRespiratoria.html"),u="#freqRespiratoria",l={playing:0,stopped:1},d=l.stopped,g={last:void 0,passed:void 0,now:void 0,accumulator:0,time:void 0,rate:60},f={x:700,y:300,radius:60,angle:0,line:20,img:void 0,accumulator:0,time:1};g.time=1e3/g.rate;var x=new e;x.x=50,x.y=180,x.width=400,x.height=240,x.srWidth=1920,x.srHeight=1152,x.frameTotal=12,x.cyclesPerMinute=18,x.frameTime=6e4/x.cyclesPerMinute/x.frameTotal;var p=0;for(i=0;i<x.frameTotal;i++){x.img.push(new Image),x.img[i].onload=function(){p++};var y=x.img[i];i<10&&(i="0"+i),y.src="./images/modalScenes/01_"+i+".png"}return f.img=new Image,f.img.src="./images/modalScenes/relogioDigital.png",f.img.onLoad=function(){},{init:a,setFr:m,open:r,close:o}});