/**
 * @author Otho - Marcelo Lopes Lotufo
 */
define(function() {

    var baseDir = "./images/";
    var paths = {
        others: [
            // "./assets/images/misc/arrow-icon_button-hover.png",
            // "./assets/images/misc/arrow-icon_button.png",
            // "./assets/images/misc/button-bg.png",
            // "./assets/images/misc/shattered.png",
            // "./assets/images/action_buttons/abrir_dialogo.jpg",
            // "./assets/images/action_buttons/anotarProntuario.jpg",
            // "./assets/images/action_buttons/confirmar_pulseira.jpg",
            // "./assets/images/action_buttons/examinar_paciente.jpg",
            // "./assets/images/action_buttons/gaveta.jpg",
            // "./assets/images/action_buttons/ir_corredor.jpg",
            // "./assets/images/action_buttons/ir_leito.jpg",
            // "./assets/images/action_buttons/ir_posto_de_enfermagem.jpg",
            // "./assets/images/action_buttons/ir_recepcao.jpg",
            // "./assets/images/action_buttons/ir_sala_de_leitos.jpg",
            // "./assets/images/action_buttons/lavarMaos.jpg",
            // "./assets/images/action_buttons/leito-char-01.jpg",
            // "./assets/images/action_buttons/leito-char-02.jpg",
            // "./assets/images/action_buttons/mudar_posicao_paciente.jpg",
            // "./assets/images/action_buttons/oximetro.jpg",
            // "./assets/images/action_buttons/posicionar_coxim.jpg",
            // "./assets/images/action_buttons/pressao.jpg",
            // "./assets/images/action_buttons/prontuario-confirma.jpg",
            // "./assets/images/action_buttons/prontuario-original.jpg",
            // "./assets/images/action_buttons/prontuario.jpg",
            // "./assets/images/action_buttons/pulseira.jpg",
            // "./assets/images/action_buttons/relogio.jpg",
            // "./assets/images/action_buttons/sem-imagem.jpg",
            // "./assets/images/action_buttons/termometro.jpg",
            // "./assets/images/action_buttons/voltar_menu.jpg",
            // "./assets/images/characters/char-jogador.jpg",
            // "./assets/images/characters/char-mentor.jpg",
            // "./assets/images/characters/char-paciente-01.jpg",
            // "./assets/images/characters/char-paciente-02.jpg",
            // "./assets/images/characters/char-recepcionista.jpg",
            // "./assets/images/characters/mentor.png",
            // "./assets/images/characters/recepcionista.png",
            // "./assets/images/interactiveObjects/bg_lateral_dir.png",
            // "./assets/images/interactiveObjects/bg_lateraL_esq.png",
            // "./assets/images/interactiveObjects/char-mentor-hover.png",
            // "./assets/images/interactiveObjects/char-mentor.png",
            // "./assets/images/interactiveObjects/checkmark-gray.png",
            // "./assets/images/interactiveObjects/checkmark.png",
            // "./assets/images/interactiveObjects/confirmar_pulseira.png",
            // "./assets/images/interactiveObjects/coxim-hover.png",
            // "./assets/images/interactiveObjects/coxim.png",
            // "./assets/images/interactiveObjects/intObj-receptionist.png",
            // "./assets/images/interactiveObjects/oximetro-hover.png",
            // "./assets/images/interactiveObjects/oximetro.png",
            // "./assets/images/interactiveObjects/pressao-hover.png",
            // "./assets/images/interactiveObjects/pressao.png",
            // "./assets/images/interactiveObjects/pulseira-paciente01.png",
            // "./assets/images/interactiveObjects/relogio-hover.png",
            // "./assets/images/interactiveObjects/relogio.png",
            // "./assets/images/interactiveObjects/termometro-hover.png",
            // "./assets/images/interactiveObjects/termometro.png",
            // "./assets/images/modalScenes/gaveta.png",
            // "./assets/images/modalScenes/medidorPressao.png",
            // "./assets/images/modalScenes/oximetro.png",
            // "./assets/images/modalScenes/pulseira.png",
            // "./assets/images/modalScenes/relogioDigital.png",
            // "./assets/images/modalScenes/termometro.png",
            // "./assets/images/scenes/alaMasculina-paciente-virado.jpg",
            // "./assets/images/scenes/alaMasculina.jpg",
            // "./assets/images/scenes/corredor.jpg",
            // "./assets/images/scenes/encerra-provisoria-alfa.jpg",
            // "./assets/images/scenes/fim-level.jpg",
            // "./assets/images/scenes/leito-char-01.jpg",
            // "./assets/images/scenes/leito-char-02-coxim.jpg",
            // "./assets/images/scenes/leito-char-02-virado.jpg",
            // "./assets/images/scenes/leito-char-02.jpg",
            // "./assets/images/scenes/postoDeEnfermagem.jpg",
            // "./assets/images/scenes/recepcao.jpg",
            "./images/scenes/salaDeLeitos.jpg"
        ]
    };

    return {
        paths: paths,
        baseDir: baseDir
    };
});
