/**
 * @author Otho - Marcelo Lopes Lotufo
 */
define(function () {

	var baseDir = "./assets/images/";
	var paths = {
        scenes:{
            recepcao: "scenes/recepcao.jpg"
        },
        others: [
            "./assets/images/action_buttons/sem-imagem.jpg",
            "./assets/images/action_buttons/sem-imagem-disabled.jpg",
            "./assets/images/arrow-icon_button.png",
            "./assets/images/arrow-icon_button-hover.png",
            "./assets/images/button-bg.png",
            "./assets/images/shattered.png",
            "./assets/images/scenes/abertura-provisoria.jpg",
            "./assets/images/scenes/posto_de_enfermagem.jpg",
            "./assets/images/scenes/ala_masculina.jpg",
            "./assets/images/scenes/sala_de_leitos.jpg",
            "./assets/images/scenes/leito-char-01.jpg",
            "./assets/images/scenes/leito-char-02.jpg",
            "./assets/images/scenes/corredor.jpg",
            "./assets/images/scenes/fim-level.jpg",
            "./assets/images/scenes/leito-char-02-virado.jpg",
            "./assets/images/scenes/leito-char-02-coxim.jpg",
            "./assets/images/scenes/ala_masculina-paciente-virado.jpg",
            "./assets/images/scenes/encerra-provisoria-alfa.jpg",
            "./assets/images/modalScenes/gaveta.png",
            "./assets/images/modalScenes/pulseira.png",
            "./assets/images/modalScenes/carlos-esme-gouvea.jpg",
            "./assets/images/modalScenes/prontuario_carlos.jpg",
            "./assets/images/modalScenes/prontuario_joao.jpg",
            "./assets/images/interactiveObjects/bg_lateral_esq.png",
            "./assets/images/interactiveObjects/bg_lateral_dir.png",
            "./assets/images/interactiveObjects/termometro.png",
            "./assets/images/interactiveObjects/termometro-hover.png",
            "./assets/images/interactiveObjects/pressao.png",
            "./assets/images/interactiveObjects/pressao-hover.png",
            "./assets/images/interactiveObjects/oximetro.png",
            "./assets/images/interactiveObjects/oximetro-hover.png",
            "./assets/images/interactiveObjects/char-mentor.png",
            "./assets/images/interactiveObjects/char-mentor-hover.png",
            "./assets/images/interactiveObjects/confirmar_pulseira.png",
            "./assets/images/interactiveObjects/coxim.png",
            "./assets/images/interactiveObjects/coxim-hover.png",
            "./assets/images/characters/char-recepcionista.jpg",
            "./assets/images/characters/char-mentor.jpg",
            "./assets/images/characters/char-paciente-01.jpg",
            "./assets/images/characters/char-paciente-02.jpg",
            "./assets/images/characters/char-jogador.jpg",
            "./assets/images/action_buttons/ir_corredor.jpg",
            "./assets/images/action_buttons/ir_corredor-disabled.jpg",
            "./assets/images/action_buttons/ir_posto_de_enfermagem.jpg",
            "./assets/images/action_buttons/ir_posto_de_enfermagem-disabled.jpg",
            "./assets/images/action_buttons/ir_recepcao.jpg",
            "./assets/images/action_buttons/ir_recepcao-disabled.jpg",
            "./assets/images/action_buttons/ir_sala_de_leitos.jpg",
            "./assets/images/action_buttons/ir_sala_de_leitos-disabled.jpg",
            "./assets/images/action_buttons/abrir_dialogo.jpg",
            "./assets/images/action_buttons/abrir_dialogo-disabled.jpg",
            "./assets/images/action_buttons/examinar_paciente.jpg",
            "./assets/images/action_buttons/examinar_paciente-disabled.jpg",
            "./assets/images/action_buttons/lavar_maos.jpg",
            "./assets/images/action_buttons/lavar_maos-disabled.jpg",
            "./assets/images/action_buttons/gaveta.jpg",
            "./assets/images/action_buttons/termometro.jpg",
            "./assets/images/action_buttons/pressao.jpg",
            "./assets/images/action_buttons/oximetro.jpg",
            "./assets/images/action_buttons/anotar_prontuario.jpg",
            "./assets/images/action_buttons/anotar_prontuario-disabled.jpg",
            "./assets/images/action_buttons/prontuario.jpg",
            "./assets/images/action_buttons/prontuario-disabled.jpg",
            "./assets/images/action_buttons/prontuario-confirma.jpg",
            "./assets/images/action_buttons/prontuario-confirma-disabled.jpg",
            "./assets/images/action_buttons/pulseira.jpg",
            "./assets/images/action_buttons/pulseira-disabled.jpg",
            "./assets/images/action_buttons/confirmar_pulseira.jpg",
            "./assets/images/action_buttons/confirmar_pulseira-disabled.jpg",
            "./assets/images/action_buttons/leito-char-01.jpg",
            "./assets/images/action_buttons/leito-char-01-disabled.jpg",
            "./assets/images/action_buttons/leito-char-02.jpg",
            "./assets/images/action_buttons/leito-char-02-disabled.jpg",
            "./assets/images/action_buttons/posicionar_coxim.jpg",
            "./assets/images/action_buttons/posicionar_coxim-disabled.jpg",
            "./assets/images/action_buttons/mudar_posicao_paciente.jpg",
            "./assets/images/action_buttons/mudar_posicao_paciente-disabled.jpg",
            "./assets/images/action_buttons/voltar_menu.jpg"
        ]
	};

	return {
        paths: paths,
        baseDir: baseDir
    };
});